app.security.enabled=true

spring.jpa.show-sql=false
logging.level.root=WARN
management.endpoint.health.show-details=never

spring.datasource.hikari.pool-name=FincasProdPool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=10000
