app.security.enabled=true
app.demo.password=${DEMO_PASSWORD:}

spring.jpa.show-sql=false
logging.level.co.sena.adso.porteria=DEBUG

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.datasource.hikari.pool-name=PorteriaDevPool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
