app.security.enabled=true
app.demo.password=

spring.jpa.show-sql=false
logging.level.root=WARN
management.endpoint.health.show-details=never

spring.datasource.hikari.pool-name=PorteriaProdPool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
