spring.application.name=fincas-api
server.port=${SERVER_PORT:31026}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Las variables se leen del .env que está en la raíz del proyecto
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:adso_fincas}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

spring.jackson.time-zone=America/Bogota
spring.data.web.pageable.max-page-size=100

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

management.endpoints.web.exposure.include=health,info

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
